//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorPrescription
    {
        public int DoctorPrescriptionID { get; set; }
        public int ScheduleID { get; set; }
        public int DrugID { get; set; }
        public string Description { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
