//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugRequest
    {
        public int DrugRequestID { get; set; }
        public int PhysicianID { get; set; }
        public string DrugInfoText { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public string RequestStatus { get; set; }
    
        public virtual Physician Physician { get; set; }
    }
}
