//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianAdvice
    {
        public int PhysicianAdviceID { get; set; }
        public int ScheduleID { get; set; }
        public string Advise { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
