//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTable
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public Nullable<int> Reference_ID { get; set; }
    }
}
